CUDA_VISIBLE_DEVICES=0 python run_docvqa.py \
    --data_dir data/ \
    --model_type layoutlm \
    --model_name_or_path model/ \
    --do_lower_case \
    --max_seq_length 512 \
    --do_train \
    --num_train_epochs 15 \
    --logging_steps 500 \
    --evaluate_during_training \
    --save_steps 500 \
    --do_eval \
    --output_dir  ./data/output/ \
    --per_gpu_train_batch_size 8 \
    --overwrite_output_dir \
    --cache_dir ./data/models/ \
    --skip_match_answers \
    --val_json ./dataset_processed/val/val_v1.0.json \
    --train_json ./dataset_processed/train/train_v1.0.json